### PR TITLE
Dragonflight/RubyLifePools/Trash: Lightning Storm timer

### PR DESCRIPTION
**Pull request by kpontussvensson**
Added a timer for Lightning Storm, helps for healers who need to ramp to out heal it. The CD seems to be 20s but can be delayed by spell queueing etc.

### CODE REVIEW

**Comment by kpontussvensson** [comment]
Okay, but are people chaining the most dangerous mob in the entire instance? I'm fine to keep this locally if you don't want to add it to the addon as it is, or is there perhaps an easy way to use the bigwigs api to create a bar locally from a weakaura?

I use the spell cds on nameplates weakaura already but I find it easier to ramp with the big wigs timers.

**Comment by ntowle** [comment]
You could create a bar from a WeakAura by creating a Combat Log trigger for the Lightning Storm spell cast start:

```
local mod = BigWigs:GetBossModule("Ruby Life Pools Trash", true)
if mod then 
    mod:Enable()
    mod:Bar(392486, 20.0)
end
```

You could do something similar from a WeakAura using Combat Log for Unit Died to stop the bar.

**Comment by kpontussvensson** [comment]
Thanks a lot! I actually tried to do something like that before I just decided to modify LittleWigs instead. Will fix a weakaura for it instead then so I don't have to worry about keeping my local file up to date.

**Comment by funkydude** [comment]
Just to reiterate: For this to be merged you'd need to use nameplate bars. If that's not what you want, remember to close this.

**Pull request closed without merging**
