### PR TITLE
CourtOfStars/Trash: do not show messages for buffs that were already used

### PR DESCRIPTION
**Pull request by Zireael-N**

### CODE REVIEW

**Comment by elvador** [comment]
For which buffs is this actually a problem?
IIRC the items become unuseable/unhoverable after they're used anyway.

**Comment by elvador** [comment]
Okay, that's fine then. But the buff check should be `usableFound` and not in `announceUsable`.
Would be appreciated if you test it after the changes.

**Comment by elvador** [comment]
Let me know when it's tested.

**Comment by Zireael-N** [comment]
I tested the lantern and refreshments before pushing a commit, no messages if you have corresponding buffs.

Maybe there's a better way to handle this. I noticed that this problem is present for "Discarded Junk" (hunters'/blacksmiths' trap), but it does not give a buff. Your cursor changes to a cogwheel if it's over an item that can still be used but stays the same if the item was used, not sure if there's an API that can check for this.

**Comment by elvador** [comment]
Not sure if I understand it correctly: After being activated and killing an add, the trap can still be clicked? Unless it gets a (de)buff I don't think there is a simple way to check for that.

But I don't think it's a big issue in general. We already have a 5 minute anti spam check, so it shouldn't print the wrong message that often.

**Comment by Zireael-N** [comment]
It can't be clicked but it stays there and triggers `UPDATE_MOUSEOVER_UNIT`.

**Comment by elvador** [comment]
I couldn't find any API to check if it's intractable/usable, so it will stay like it is for now.

**Pull request merged**
