### PR TITLE
BlackRookHold/Trash  Risen Archer Shoot added

### PR DESCRIPTION
**Pull request by Soreox**
Risen Archer. Shoot on YOU! added

### CODE REVIEW

**Comment by elvador** [comment]
Did you test this in-game? 

Looking at some top ranks on WarcraftLogs it looks like this spell is cast way to often to warn and have a say for it: https://www.warcraftlogs.com/reports/zhVLTK7dHbNfkxM3#fight=3&type=casts&hostility=1&ability=193633&view=analytical

There are also a lot of mistakes in your file:
1. The option key should be below Arrow Barrage (Risen Archer), to fix the grouping.
2. `mod:Shoot` is declared twice.
3. `mod:Casts` is not used.
4. `self:Say` will only work when the option key has the `SAY` flag.

**Comment by Soreox** [comment]
works fine for me in-game it's pretty much a copy of Crackle in HoV trash.

**Comment by elvador** [comment]
Those spells are handled differently.

Crackle:
- Can't be cc'd.
- Can be avoided by side stepping - thus a warning for nearby players (say) is useful.

Shoot:
- Can be cc'd (stuns, disorients, maybe others).
- Can't be avoided when it's cast.
- Only hits one player (the target => a say message is not useful there).

On which difficulty did you test this?

**Comment by Soreox** [comment]
tested in m+

**Comment by elvador** [comment]
Imo it will be too much spam and without much use.

I'm gonna let the other devs decide on it.

PS: Those mistakes I mentioned in my previous comments will need to be addressed before this will be considered to merge.

**Pull request closed without merging**
