### PR TITLE
Edit for missing legion locale files

### PR DESCRIPTION
**Pull request by WetU**

### CODE REVIEW

**Comment by funkydude** [comment]
Why are there edits for the boss module files?

**Comment by WetU** [comment]
@funkydude 
They has locale strings, but no created related files.
so making them.

**Comment by funkydude** [comment]
I don't see any difference in Trash.lua for example, what did you change?

**Comment by WetU** [comment]
Original module files are not changed.
I uploaded changed files included original module files.
I don't know why difference

**Pull request closed without merging**
