### PR TITLE
Shadowlands/Plaguefall/Trash: Warn when Stealthlings spawn

### PR DESCRIPTION
**Pull request by redcatelf**
This adds https://www.wowhead.com/spell=328400/stealthlings

Stealthlings need revealing by a mobile class with AoE, and/or CC'ing e.g. with Ursols Vortex or Binding Shot, so I think they're worth adding to LittleWigs for sure.

Untested, but ID is per my logs, and it's the same implementation as Enveloping Webbing.

I wasn't sure about the color and sound. I went with red and long, since Enveloping Webbing already uses alarm.

### CODE REVIEW

**Comment by Zireael-N** [comment]
I don't remember if this ability can be interrupted but if not, I suggest switching to a `SPELL_CAST_SUCCESS` event. 

The third argument in the `self:Message()` call needs to be either `CL.casting:format(args.spellName)` (if we use `SPELL_CAST_START`) or `CL.spawned:format(args.spellName)` (if we switch). If I saw a message saying "Stealthlings", I would assume that they already spawned.

I also suggest using `warning` as the sound, it warrants an instant switch / AoE stun on higher Fortified keys.

**Comment by redcatelf** [comment]
> I don't remember if this ability can be interrupted but if not, I suggest switching to a SPELL_CAST_SUCCESS event.

It can't be interrupted, and if stunned it recasts, so I changed to SPELL_CAST_SUCCESS.

I think there's perhaps a general conversation worth having about allowing earlier notifications (like on cast start). As a voice plugin user, if the TTS voice says "Stealthlings" at the start of the cast, by the time the word has registered in my brain, the cast is already over. Also, as a caster, I cannot react immediately, so it's better to be notified earlier than later. But for a tank who's using Sounds instead of Voices, hearing the sound on SPELL_CAST_SUCCESS is surely preferable.

Anyways, back to the PR at hand...

> I also suggest using warning as the sound, it warrants an instant switch / AoE stun on higher Fortified keys.

Done!

Can you take a look again please?

**Comment by Zireael-N** [comment]
I changed the key to a custom one, since 328400 has an empty description.

**Comment by Zireael-N** [comment]
Thanks!

**Pull request merged**
