### PR TITLE
Legion/CourtOfStars/Trash: Update spy event helper

### PR DESCRIPTION
**Pull request by ntowle**

### CODE REVIEW

**Comment by MysticalOS** [comment]
Just wanted to add a note of an issue me and artemis already got with new code. Some weak auras for M+ (often without even user knowledge such as the common M+ timer aura) are auto selecting gossip immediately and going to text dialog, and when this happens BW and DBM cant' read the gossip ids at all since it was already dismissed by the WA.

Basically, the issue DBM used to cause when it stupidly called "close" when it was done with dialog :D (which is fixed now).

I suppose LW might still avoid issue with way it unregisters other mods from screwing with gossip but I thought it was still worth noting still. We might have to fix issue doing same thing which is a crappy work around but if people are running tons of popular weak auras that are doing old string method, then they'll break our better gossipID method every time :\

**Comment by MysticalOS** [comment]
https://wago.io/M+Timer/114

https://wago.io/dfdungeons

So far have been found to auto select clue gossip and advance to text selection and prevent reading gossip Ids.

**Comment by ntowle** [comment]
I think the unregistering and reregistering LW does should take care of that by ensuring LW handles the event first, but I can test with a few of the popular WAs to confirm. Although this PR maintains the existing behavior of auto-gossiping so if for some reason someone is running both DBM and LW only one would have time to grab the gossip ID most likely. I didn't view this as an issue because of the existing sync but let me know if you see problems with this approach.

**Comment by MysticalOS** [comment]
Yeah I think as long as LW or DBM handle it first the weak auras that auto select gossip and advance to text won't break us. I saw issue affecting us but realized after posting here that it probably won't affect LW due to your fix to work around DBMs earlier bad behavior :D

**Comment by MysticalOS** [comment]
Found. bug with this approach that's easy to address.

Demon hunters can only use spectral sight to reveal spy after 5 clues have been discovered. The probelm is the clues dn't flag discovered until you CHOOSE the dialog option for all 5. this means that DBM and LW just reading the gossip ID and not actually advancing gossip doesn't trigger the flag the zone checks for spectral sight. So basically after we grab gossip ID, we still need to advance it to text for Demon hunters :)

So yeah make you still use SelectGossipID after getting gossip ID. It does mean though that any other WA or addon using gossip IDs is still cucked from doing so if user is running multiple, but as long as DBM or LW is first, it doesn't matter which one does it.

**Pull request merged**
