### PR TITLE
Readd support for Mage Tower

### PR DESCRIPTION
**Pull request by vivianig**
I've readded the Mage Tower files that had been removed in 7881141, and updated them to work properly with the current LittleWigs version (9.1.4)

Do note that this also requires two changes in [BigWigs loader.lua](https://github.com/BigWigsMods/BigWigs/blob/master/Loader.lua) to load the Mage Tower module correctly:~~
`Line 130: + [1716]=true, -- Broken Shore Mage Tower`
`Line 290: + [1716] = lw_l, -- Broken Shore Mage Tower (Fake Menu)`

I've tested that the module loads properly both in the GUI and during the encounters. I still need to test if the timers are still correct.

### CODE REVIEW

**Comment by vivianig** [comment]
Going to handle the errors and push another commit 👍

**Comment by nebularg** [comment]
Thanks! I was about to start work on this 😝 Looks like the only other thing you need to fix is add some lines to the toc so the modules show up in the options

```diff
--- a/LittleWigs_Legion.toc	Sat Dec 11 18:55:47 2021
+++ b/LittleWigs_Legion.toc	Sat Dec 11 18:56:19 2021
@@ -16,6 +16,8 @@
 ## Dependencies: BigWigs
 
 ## X-Category: Party
+## X-BigWigs-ExtraMenu: 1716
+## X-BigWigs-NoMenu: 1616, 1673, 1684, 1698, 1702, 1703, 1710
 ## X-BigWigs-LoadOn-InstanceId: 1456, 1466, 1477, 1458, 1492, 1493, 1501, 1516, 1544, 1571, 1616, 1651, 1673, 1677, 1684, 1698, 1702, 1703, 1710, 1753
 
 modules.xml
```

**Comment by vivianig** [comment]
Oh is that the proper way to have it loaded? I don't know my way around and I just forced loaded it from the main BW loader 😅 

I've fixed most of the stuff, the only one I'm not sure how to go about is 
`Legion/ArtifactScenarios/Raest.lua:111: Missing icon! func=mod:UNIT_SPELLCAST_SUCCEEDED, key="rune", text="rune", icon=nil`

Unfortunately I'm not familiar enough with the API to figure out how to fix it.

**Comment by nebularg** [comment]
Should be `self:Flash("rune", spellId)`

**Comment by vivianig** [comment]
Alright this should be all to fix the errors

**Pull request merged**
