### PR TITLE
Cataclysm/VortexPinnacle/Altairus: Improve Call the Wind timer

### PR DESCRIPTION
**Pull request by Causese**

### CODE REVIEW

**Comment by Justw8** [comment]
We generally start counters at 1 and increment after the message/sound and before the new bar so we can always use that counter on bars if needed.

Could you update it to use that logic? :)

**Comment by Causese** [comment]
You're lying! :) 

LittleWigs seem to do things differently

**Comment by ntowle** [comment]
I'll admit to liking starting at 0 and having the counter be "how many of these have happened" with bars at +1.

**Comment by Justw8** [comment]
Gross.

**Comment by ntowle** [comment]
I think I've been outvoted @Causese, can you change it?

**Comment by Causese** [comment]
seems like they made a bunch of changes to the dungeons including these timers

**Pull request merged**
