### PR TITLE
Update ptBR

### PR DESCRIPTION
**Pull request by renannmp**

### CODE REVIEW

**Comment by Zireael-N** [comment]
This option does not include timers, my bad. Could you please update the translation?

**Comment by renannmp** [comment]
Done.

**Comment by Zireael-N** [comment]
I changed the English description to a better one, let me know if the current translation sounds fine in Portuguese (I assume it's a 1:1 translation) or if you want to mirror the changes.

**Comment by renannmp** [comment]
Ok, it's all good now, just updated it to reflect the new desciption. Thank you.

**Comment by Zireael-N** [comment]
Thanks!

**Pull request merged**
