### PR TITLE
Fix warm up timer for Agatha.

### PR DESCRIPTION
**Pull request by ChrisKader**

### CODE REVIEW

**Comment by Justw8** [comment]
I can't confirm it, but going to trust this one :)

**Comment by nebularg** [comment]
This is wrong

**Comment by ChrisKader** [comment]
The 35 second timer shows up when warmup_trigger2 is supposed to show.

https://streamable.com/a1je6n

**Comment by ChrisKader** [comment]
@nebularg

**Comment by nebularg** [comment]
I'm going to go with you didn't have the updated module? It matches the trigger text, so i'm not sure how it could show the wrong time. https://www.youtube.com/watch?v=ht8wnZD9V-E shows enabling right away, then another attempt enabling after the first voice line (which shows how off 15s is, I bumped that up in the released version)

**Pull request merged**
