### PR TITLE
DarkheartThicket/ShadeOfXavius: warn about incoming party-wide damage at 50%

### PR DESCRIPTION
**Pull request by Zireael-N**

### CODE REVIEW

**Comment by funkydude** [comment]
51.9% is cutting it pretty close.
There's a warning for it coming soon but no warning for it casting?
Expanding on above, you can use the same function to unregister the health event to prevent a possibility of printing the soon message after the cast has happened.

**Comment by Zireael-N** [comment]
It isn't an instant cast, he's usually at 45% on high Tyrannical keys by the time the explosion goes off.
I am not sure how to track the actual cast, you can see him waving his hands but there's no cast bar, so I assume there are no `SPELL_CAST_*` events either.

**Comment by Zireael-N** [comment]
Just checked him out, `SPELL_CAST_*` events are not present, `UNIT_SPELLCAST_SUCCEEDED` only fires after the explosion goes off.

**Comment by funkydude** [comment]
Then I assume the spell id you've chosen was at random, because it doesn't have the best description. Doesn't 200050 make more sense?

**Comment by Zireael-N** [comment]
Yeah, seems to be a better choice. Changed.

**Pull request merged**
