### PR TITLE
Court of Stars Trash: Remove the alerts for abilities that are incons…

### PR DESCRIPTION
**Pull request by cexikitin**
…equential

### CODE REVIEW

**Comment by funkydude** [comment]
Keep in mind that not everything needs removed. Lower priority warnings can have their sounds removed to reduce obtrusiveness, or restricted to specific roles.

That being said, I'd like the opinion of @amki on these changes as I believe we may need to find a middle ground with a compromise on both ends.

**Comment by roionsteroids** [comment]
Look at a higher level mythic+ damage taken log and you'll see how very consequential these are. That being said, a bit spammy when doing large pulls. I can definitely see it being too much at normal mythic level.

Currently quickest level 15 CoS on warcraftlogs: https://www.warcraftlogs.com/reports/rza1PvqQgnKXCycM#fight=20&type=damage-taken&by=ability

Your reasoning behind classifying many of these spells as inconsequential is mindblowing, for example Quelling Strike is like a worse version of Bonebreaking Strike in BRH (2 million damage per hit, 4 seconds stun). Searing Glare (can be interrupted) deals nearly a million damage to everyone in non-fortified. Drifting Embers from multiple non-interrupted/cc'd imps can wipe a group within a few seconds. Charged Blast (again, can be interrupted) dealt 2 million damage to the tank. Mana Fang (can be dispelled) is among the top damage taken abilities. I could go on, but I hope you get it by now.

In any case, instead of removing these spells, why not simply disable them by default, but leave it optional for people who want it?

For the record, I wrote the module, @amki submitted it for me. I've done some changes in my local version, going to run CoS a few times and check for improvements.

**Comment by cexikitin** [comment]
I've been doing them +9-12 in large pulls and it is way too much information at that level.  Perhaps my group is just better at interrupting as I only kept things that we took significant damage from each round.

I wanted to reduce the number of alerts to levels similar to BRH and VOW where not every single thing with a cast has an alert.

**Comment by roionsteroids** [comment]
Drifting Embers/Wild Detonation definitely needs a rate limiter, that tiny change alone will limit *spam* by a lot. Not sure if I fucked up something in the DispellableDebuffs section, I think it triggers for everyone right now, regardless of whether you can dispel it or not.

**Comment by cexikitin** [comment]
Felblaze Puddle is annoying as its constantly going off, and does little damage.
Eye Storm is only stoppable by death knights with a grip
Bewitch is annoying, but doesn't do any damage

I think these three are the most annoying ones. If you pull the two pack after the first inquisitor plus the bridge you just get totally overloaded with alerts.

**Comment by roionsteroids** [comment]
In theory the puddle warning should only trigger every 1.5 seconds at most, which doesn't seem to match reality for whatever reason. Oh, it applies a 12 seconds debuff when hit, but doesn't actually deal more damage while standing in the puddle, just prolongs the debuff? Let me see...

Eye Storm can be stopped by stunning before the cast goes off iirc.

Bewitch, while annoying, is likely not worth a say/flash, changed its category.

Going to test it with http://paste2.org/M5JGxKs2 (github comment formatting, even as "code" is somehow all fucked up).

Also added some other stuff like Eye Storm and Disintegration Beam hopefully disappearing on death.

**Comment by roionsteroids** [comment]
Much less spammy, however few things didn't work, next try: http://paste2.org/Lb9MOvCs.

**Comment by funkydude** [comment]
If communication on these changes is over then I'll merge this as-is, because after doing CoS today, the current module is intolerable.

**Comment by cexikitin** [comment]
I think even with the last iteration is way too much.

**Comment by nebularg** [comment]
The throttle was just a quick fix, update your branch and we'll still merge

**Comment by nebularg** [comment]
<elvador> looking at that pr it removed some important abilities

he didn't elaborate, though

**Comment by elvador** [comment]
The problem with this issue is that it comes down to personal preference.

Looking at the log @roionsteroids provided, it's pretty clear that if you interrupt/stun/disorient the important abilities, they don't do damage at all. But that doesn't mean that we shouldn't announce them: If a less experienced group is doing CoS they might be single pulling the groups, maybe even cc'ing some mobs and they want to have some assistance via LittleWigs.
On the other side are the rushing boost/guild groups who are pulling a lot of trash packs together. They don't care about every single ability. They just stun the mobs and kill them in a few seconds.

Like @nebularg said: The throttle I pushed yesterday was a quick fix. I ran some CoS keys after it and the improvement was immense. I also didn't know that there was a active PR on this issue, I should've looked at it sooner.

That being said, we always want to improve our mods. So please tell us the abilities you want to be removed from LittleWigs and we can discuss on them.

**Comment by funkydude** [comment]
I don't see any issues with this PR. Please elaborate on exactly what abilities need to stay so they can be re-added.

**Comment by roionsteroids** [comment]
Could gather better feedback when using the latest version I posted a whole month ago (it did contain not only throttles for certain abilities such as Wild Detonation and Drifting Embers, but also various spell fixes and improvements).

http://paste2.org/gNDD787P is the combined file, including elvadors throttles.

Is the module still one of the more extensive ones? Yes. Is Court of Stars pretty much the most punishing dungeon for ignored casts? Also yes. This should be considered. I recommend running two +15s with and without this module ;)

**Comment by cexikitin** [comment]
I think yours still has too much stuff. I've tanked and dps +18 COS.

I als don't think mine needs the throttle logic as nothing in there gets spammed?

**Comment by cexikitin** [comment]
When you pull 4 or 5 packs together, you really don't want 5 alarms going off nonstop.

**Comment by Nevcairiel** [comment]
I fully agree that CoS has way too many warnings for way too much stuff, at the very least the default /say announces for a lot of the things should be removed - /say should be reserved for things where everyone around me needs to pay attention by moving, not for random debuffs that require nothing but healing.

**Comment by Justw8** [comment]
I've reduced a number of warnings and messages in the module, should be a lot less spammy and warning you with non-essential information.

**Comment by funkydude** [comment]
Thanks for the work. Nothing is really coming of this though, and I assume people are happy with the current state.

**Pull request closed without merging**
