### PR TITLE
Classic: implement missing Dungeons/Bosses

### PR DESCRIPTION
**Pull request by Avyiel**
This PR aims to refactor the UBRS module for Classic. That means adding all dungeons bosses and relevant mechanics.

- [ ] Blackfathom Depths
- [ ] Blackrock Dephts
- [ ] Deadmines
- [ ] Dire Maul
- [ ] Gnomeregan
- [x] Lower Blackrock Spire
- [ ] Maraudon
- [x] Ragefire Chasm
- [ ] Razorfen Downs
- [ ] Razorfen Kraul
- [ ] Scarlet Monastery
- [ ] Scholomance
- [ ] Shadowfang Keep
- [ ] Stockades
- [ ] Stratholme
- [ ] Sunken Temple
- [ ] Uldaman
- [x] Upper Blackrock Spire
- [ ] Wailing Caverns
- [ ] Zul'Farrak

### CODE REVIEW

**Comment by nebularg** [comment]
A few things

1) Second arg to :NewBoss is the instance id, so all Ragefire Chasm bosses should be 389 for example (not sure where you got the values you use)
2) Unless dungeon bosses have an ENCOUNTER_START/ENCOUNTER_END, you won't get an Engage/Wipe stuff without using `CheckForEngage`/`CheckForWipe`, which is probably the most annoying thing about classic dungeons
3) For new modules, you should be using the two "modern" message APIs (`Message2`, `TargetMessage2`). They remove the sound param, so you also need to call `:PlaySound` directly

**Comment by Avyiel** [comment]
> 1. Second arg to :NewBoss is the instance id, so all Ragefire Chasm bosses should be 389 for example (not sure where you got the values you use)

Right, I took the values for "Zone ID" I found in WoWhead, should I use these ones (https://wow.gamepedia.com/InstanceID) instead?

> 2\. Unless dungeon bosses have an ENCOUNTER_START/ENCOUNTER_END, you won't get Engage/Wipe stuff without using `CheckForEngage`/`CheckForWipe`/message triggers, which is probably the most annoying thing about classic dungeons

Meaning a lot of manual work for me then. I'll try to come up with some detection, I'll probably need some guidance later on anyway.

> 3\. For new modules, you should be using the two "modern" message APIs (`Message2`, `TargetMessage2`). They remove the sound param, so you also need to call `:PlaySound` directly

Alright, I'll keep that in mind. Use the "new" ones for things that don't need sounds!

**Comment by nebularg** [comment]
> Right, I took the values for "Zone ID" I found in WoWhead, should I use these ones (https://wow.gamepedia.com/InstanceID) instead?

You can use that for the dungeons that were not updated in retail, https://wow.tools/dbc/?dbc=map&build=1.13.4.34835 will let check the game data

> Alright, I'll keep that in mind. Use the "new" ones for things that don't need sounds!

Should always use them :p

**Comment by Avyiel** [comment]
> > Right, I took the values for "Zone ID" I found in WoWhead, should I use these ones (https://wow.gamepedia.com/InstanceID) instead?
> 
> You can use that for the dungeons that were not updated in retail, https://wow.tools/dbc/?dbc=map&build=1.13.4.34835 will let check the game data
> 
> > Alright, I'll keep that in mind. Use the "new" ones for things that don't need sounds!
> 
> Should always use them :p

Gotcha

**Pull request closed without merging**
